fix: rewriting for better understanding
Signed-off-by: matttrach <matt.trachier@suse.com>

diff --git a/.github/workflows/validate.yaml b/.github/workflows/validate.yaml
--- a/.github/workflows/validate.yaml
+++ b/.github/workflows/validate.yaml
@@ -71,6 +71,47 @@ jobs:
             ouput="$(echo "$COMMIT" | grep -e '^fix: ' -e '^feature: ' -e '^feat: ' -e 'refactor!: ' -e 'feature!: ' -e 'feat!: ' -e '^chore(main): ')"
             return "$output"
           }
+          prefix_check() {
+            message="$1"
+            if [ "" != "$(filter "$message")" ]; then
+              echo "...Commit message does not start with the required prefix.
+              Please use one of the following prefixes: fix:, feature:, feat:, refactor!:, feature!:, feat:!.
+              'chore(main): ' is also allowed for release PRs.
+              This enables release-please to automatically determine the type of release (major, minor, patch) based on the commit message.
+              $message"
+              exit 1
+            else
+              echo "...Commit message starts with the required prefix."
+            fi
+          }
+          empty_check() {
+            message="$1"
+            if [ "" == "$message" ]; then
+              echo "...Empty commit message."
+              exit 1
+            else
+              echo "...Commit message isnt empty."
+            fi
+          }
+          length_check() {
+            message="$1"
+            if [ "$(wc -m <<<"$message")" -gt 50 ]; then
+              echo "...Commit message subject line should be less than 50 characters, found $(wc -m "$message")."
+              exit 1
+            else
+              echo "...Commit message subject line is less than 50 characters."
+            fi
+          }
+          spell_check() {
+            message="$1"
+            if [ "" != "$(aspell list <<<"$message")" ]; then
+              echo "...Commit message contains spelling errors on words: ^$WORDS\$"
+              echo "...- Also try updating the PR title not just amending the commits."
+              exit 1
+            else
+              echo "...Commit message doesnt contain spelling errors."
+            fi
+          }
 
           # Fetch the commit messages
 
@@ -79,47 +120,12 @@ jobs:
           echo "$COMMIT_MESSAGES"
 
           while read -r message; do
-            if [ "" != "$(filter "$message")" ]; then
-              echo "Commit message does not start with the required prefix.
-              Please use one of the following prefixes: fix:, feature:, feat:, refactor!:, feature!:, feat:!.
-              'chore(main): ' is also allowed for release PRs.
-              This enables release-please to automatically determine the type of release (major, minor, patch) based on the commit message.
-              $message"
-              exit 1
-            else
-              echo "Commit message $message starts with the required prefix."
-            fi
-          done <<<"$COMMIT_MESSAGES"
-
-          # Check if any commit message is empty
-          while read -r message; do
-            if [ "" == "$message" ]; then
-              echo "Found empty commit message: $message."
-              exit 1
-            else
-              echo "Commit message $message is not empty."
-            fi
-          done <<<"$COMMIT_MESSAGES"
-
-          # Check if any commit message subject line is longer than 50 characters
-          while read -r message; do
-            if [ "$(wc -m <<<"$message")" -gt 50 ]; then
-              echo "Commit message subject line should be less than 50 characters, found $(wc -m "$message"). $message"
-              exit 1
-            else
-              echo "Commit message subject line is less than 50 characters. $message"
-            fi
-          done <<<"$COMMIT_MESSAGES"
-
-          # Spell check the commit messages using aspell
-          while read -r message; do
-            if [ "" != "$(echo "$message" | aspell list)" ]; then
-              echo "Commit message $message contains spelling errors on words: ^$WORDS\$"
-              echo "Also try updating the PR title not just amending the commits."
-              exit 1
-            else
-              echo "Commit message doesnt contain spelling errors. $message"
-            fi
+            echo "checking message ^$message\$"
+            prefix_check "$message"
+            empty_check "$message"
+            length_check "$message"
+            spell_check "$message"
+            echo "message ^$message\$ passed all checks"
           done <<<"$COMMIT_MESSAGES"
 
   gitleaks:
